catalogs:
  list:
    commander: 14.0.0

nodeLinker: node-modules

plugins:
  - checksum: 2ad7c575e7f88ce57ee2dbde44d85c573b9b13cf346bcbe9841bd5da0a09c151ddde199fc4e5342048d2f0b7adc6934a34ce61bf99b9f531e9965eeac784a00a
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles/%40yarnpkg/plugin-catalogs.js"
